name:                hangman
version:             0.1.0.0
github:              "TiboStr/hangman-hs"
license:             BSD3
author:              "Tibo Stroo"
maintainer:          "Tibo Stroo"
copyright:           "2022 Tibo Stroo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TiboStr/hangman-hs#readme>

dependencies:
- base >= 4.7 && < 5
- gi-gtk == 3.0.*
- gi-gtk-hs
- haskell-gi-base
- text
- directory


library:
  source-dirs: src

executables:
  hangman-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hangman

tests:
  hangman-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hangman
